# configure server port
server:
 port: 4040

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: oracle
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
      show-sql: true